### ISSUE TITLE
retry dict is missing the mode

### ISSUE THREAD

**Issue by greut** [sbdchd/botocore-types#4]
the value is an enum: `legacy`, `standard`, and `adaptive`

```python
# config.pyi
class _RetryDict(TypedDict):
    max_attempts: int
    mode: str
```

Cheers

**Comment by sbdchd** [comment]
Thanks for the report! should be fixed in 0.2.1

**Comment by greut** [comment]
@sbdchd thanks, however I'd add the `total=False` option too. Thanks!

**Comment by sbdchd** [comment]
I've release 0.2.2 which changed the `_RetryDict` to be `total=False`

Thanks for the bug reports!
